# Generated by Django 5.1 on 2025-11-06 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("sysconfig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.ForeignKey(
                help_text="Company this user belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profiles",
                to="sysconfig.company",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_financial_year",
            field=models.ForeignKey(
                blank=True,
                help_text="Default financial year for this user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="sysconfig.financialyear",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                help_text="Associated user account",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
