# Generated by Django 5.1 on 2025-11-06 01:16

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                ("name", models.CharField(help_text="City name", max_length=100)),
                (
                    "pincode",
                    models.CharField(
                        blank=True,
                        help_text="Primary pincode for the city",
                        max_length=10,
                        validators=[apps.core.validators.validate_pincode],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether city is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "db_table": "sysconfig_city",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Country name", max_length=100, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-3 country code",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "phone_code",
                    models.CharField(
                        blank=True,
                        help_text="International dialing code (e.g., +91)",
                        max_length=10,
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        default="INR", help_text="ISO 4217 currency code", max_length=3
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        default="₹", help_text="Currency symbol", max_length=5
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether country is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "sysconfig_country",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Whether this record is soft-deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Date and time when the record was deleted",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Company legal name", max_length=200, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Company code (for internal reference)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(help_text="Registered office address")),
                (
                    "pincode",
                    models.CharField(
                        help_text="Postal pincode",
                        max_length=10,
                        validators=[apps.core.validators.validate_pincode],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Primary contact phone",
                        max_length=20,
                        validators=[apps.core.validators.validate_phone_number],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email", max_length=254
                    ),
                ),
                ("website", models.URLField(blank=True, help_text="Company website")),
                (
                    "gst_number",
                    models.CharField(
                        help_text="GST registration number",
                        max_length=15,
                        unique=True,
                        validators=[apps.core.validators.validate_gstin],
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        help_text="PAN number",
                        max_length=10,
                        unique=True,
                        validators=[apps.core.validators.validate_pan],
                    ),
                ),
                (
                    "tan_number",
                    models.CharField(
                        blank=True, help_text="TAN number (for TDS)", max_length=10
                    ),
                ),
                (
                    "cin_number",
                    models.CharField(
                        blank=True,
                        help_text="Corporate Identification Number",
                        max_length=21,
                    ),
                ),
                (
                    "established_date",
                    models.DateField(
                        blank=True, help_text="Date of establishment", null=True
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, help_text="Industry/sector", max_length=100
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo",
                        null=True,
                        upload_to="company_logos/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether company is active"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="City where company is registered",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies",
                        to="sysconfig.city",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "db_table": "sysconfig_company",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="State/Province name", max_length=100),
                ),
                ("code", models.CharField(help_text="State code", max_length=10)),
                (
                    "gst_state_code",
                    models.CharField(
                        blank=True, help_text="GST state code (for India)", max_length=2
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether state is active"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Country this state belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="sysconfig.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "db_table": "sysconfig_state",
                "ordering": ["name"],
                "unique_together": {("country", "code")},
            },
        ),
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                help_text="State this city belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="sysconfig.state",
            ),
        ),
        migrations.CreateModel(
            name="FinancialYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Whether this record is soft-deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Date and time when the record was deleted",
                        null=True,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        help_text="Financial year (e.g., 2024-2025)", max_length=9
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Start date of financial year"),
                ),
                ("end_date", models.DateField(help_text="End date of financial year")),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the active financial year",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether transactions are locked for this year",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this financial year belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_years",
                        to="sysconfig.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Year",
                "verbose_name_plural": "Financial Years",
                "db_table": "sysconfig_financialyear",
                "ordering": ["-start_date"],
                "unique_together": {("company", "year")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("state", "name")},
        ),
    ]
